--FROM SQL Server

SELECT 
[YEAR]
,[MONTH]
, 'GOVERNMENT' AS HIERARCHY
,[MONTH] AS MONTH_NUM
,CONCAT([YEAR],'-',[MONTH]) AS MONTH_ORDER
,CONCAT([YEAR], ' ', LEFT(DATENAME(MONTH, DATEFROMPARTS([YEAR], [MONTH], 1)), 3)) AS MONTH_NAME
,'MONTHLY' AS EMPLOYER_PAY_FREQUENCY
,[EMPLOYER_ID]
,1 AS "Branch_Submissions"
,FORMAT(DATEFROMPARTS([YEAR], [MONTH], [DAY]), 'yyyy-MM-dd') AS MOST_SELECTED_DATE
,1 AS NUMBER_OF_TIMES_DATE_WAS_SELECTED
, GETDATE() AS LAST_UPDATE
FROM [Barko_Reporting_DB].[Submissions].[Dtbl_Employer_Paydate]
WHERE [BRANCH] = 'GOV'
AND YEAR = '2026'