/*
DROP TABLE IF EXISTS UAT_REPLICATED_TABLES.EMPLOYER_PAYDATES_SUBMISSION_HISTORY_REPL
ON CLUSTER 'cluster1'
SYNC;
*/

CREATE TABLE UAT_REPLICATED_TABLES.EMPLOYER_PAYDATES_SUBMISSION_HISTORY_REPL
ON CLUSTER 'cluster1'
(
    YEAR UInt16,
    MONTH UInt8,
    HIERARCHY String,
    MONTH_NUM UInt8,
    MONTH_ORDER String,

    MONTH_NAME String,

    EMPLOYER_PAY_FREQUENCY LowCardinality(String),
    EMPLOYER_ID String,

    Branch_Submissions UInt32,

    MOST_SELECTED_DATE Date,

    NUMBER_OF_TIMES_DATE_WAS_SELECTED UInt32,

    LAST_UPDATE DateTime64(3)
)

ENGINE = ReplicatedReplacingMergeTree(
'/clickhouse/tables/{shard}/EMPLOYER_PAYDATES_SUBMISSION_HISTORY_REPL',
'{replica}',
LAST_UPDATE
)

PARTITION BY (YEAR, MONTH)

ORDER BY
(
    YEAR,
    MONTH,
    EMPLOYER_PAY_FREQUENCY,HIERARCHY,
    EMPLOYER_ID,
    MONTH_NAME
)

SETTINGS index_granularity = 8192;
