WITH 
toDate('2025-01-06') AS anchor_monday

INSERT INTO UAT_REPLICATED_TABLES.EMPLOYER_PAYDATE_AGGREGATED_METRICS_REPL
(
  COMPANY,
  REGION,
  AREA,
  BRANCH,
  EMPLOYER_ID,
  EMPLOYER,
  HIERARCHY_INDICATOR,
  HIERARCHY,
  PAY_FREQUENCY,
  PERIOD_START,
  PERIOD_END,
  CAPITAL_TOTAL,
  LOANS_COUNT,
  ACTIVE_BRANCHES,
  REPAYMENT_TOTAL,
  NEXT_ACTION_DATES_ARRAY,
  DATA_DATE,
  LAST_UPDATE
)

--Company Level
SELECT 
'COMPANY' AS COMPANY,
'' AS REGION,
'' AS AREA,
'' AS BRANCH,
EMPLOYER_ID,
EMPLOYER,
'COMPANY' AS HIERARCHY_INDICATOR,
'COMPANY' AS HIERARCHY,
FREQUENCY AS PAY_FREQUENCY,

addDays(
    anchor_monday,
    intDiv(
        dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
        14
    ) * 14
) AS PERIOD_START,

addDays(
    addDays(
        anchor_monday,
        intDiv(
            dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
            14
        ) * 14
    ),
    13
) AS PERIOD_END,

SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) AS LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,

today() AS DATA_DATE,
now() AS LAST_UPDATE

FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL

WHERE LOAN_STATUS IN ('CURRENT','EXPIRED')
AND FREQUENCY = 'FORTNIGHT' --AND YEAR(NEXT_ACTION_DATE) != 1970


GROUP BY
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,
PERIOD_END

--Region Level
UNION ALL

SELECT 
'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS REGION,
'' AS AREA,
'' AS BRANCH,

EMPLOYER_ID,
EMPLOYER,

'REGION' AS HIERARCHY_INDICATOR,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS HIERARCHY,

FREQUENCY AS PAY_FREQUENCY,

addDays(
    anchor_monday,
    intDiv(
        dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
        14
    ) * 14
) AS PERIOD_START,

addDays(
    addDays(
        anchor_monday,
        intDiv(
            dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
            14
        ) * 14
    ),
    13
) AS PERIOD_END,

SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) AS LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,

today() AS DATA_DATE,
now() AS LAST_UPDATE

FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL

WHERE LOAN_STATUS IN ('CURRENT','EXPIRED')
AND FREQUENCY = 'FORTNIGHT' --AND YEAR(NEXT_ACTION_DATE) != 1970

GROUP BY
REGION,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,
PERIOD_END

--Area Level
UNION ALL

SELECT 
'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS REGION,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'AreaName', CO_CODE) AS AREA,
'' AS BRANCH,

EMPLOYER_ID,
EMPLOYER,

'AREA' AS HIERARCHY_INDICATOR,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'AreaName', CO_CODE) AS HIERARCHY,

FREQUENCY AS PAY_FREQUENCY,

addDays(
    anchor_monday,
    intDiv(
        dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
        14
    ) * 14
) AS PERIOD_START,

addDays(
    addDays(
        anchor_monday,
        intDiv(
            dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
            14
        ) * 14
    ),
    13
) AS PERIOD_END,

SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) AS LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,

today() AS DATA_DATE,
now() AS LAST_UPDATE

FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL

WHERE LOAN_STATUS IN ('CURRENT','EXPIRED')
AND FREQUENCY = 'FORTNIGHT' --AND YEAR(NEXT_ACTION_DATE) != 1970

GROUP BY
REGION,
AREA,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,
PERIOD_END

--Branch Level
UNION ALL

SELECT 
'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','RegionName', CO_CODE) AS REGION,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','AreaName', CO_CODE) AS AREA,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','PastelCode', CO_CODE) AS BRANCH,

EMPLOYER_ID,
EMPLOYER,

'BRANCH' AS HIERARCHY_INDICATOR,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','PastelCode', CO_CODE) AS HIERARCHY,

FREQUENCY AS PAY_FREQUENCY,

addDays(
    anchor_monday,
    intDiv(
        dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
        14
    ) * 14
) AS PERIOD_START,

addDays(
    addDays(
        anchor_monday,
        intDiv(
            dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
            14
        ) * 14
    ),
    13
) AS PERIOD_END,

SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) AS LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,

today() AS DATA_DATE,
now() AS LAST_UPDATE

FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL

WHERE LOAN_STATUS IN ('CURRENT','EXPIRED')
AND FREQUENCY = 'FORTNIGHT' --AND YEAR(NEXT_ACTION_DATE) != 1970

GROUP BY
REGION,
AREA,
BRANCH,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,
PERIOD_END

--LC Level
UNION ALL

SELECT 
'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','RegionName', CO_CODE) AS REGION,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','AreaName', CO_CODE) AS AREA,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','PastelCode', CO_CODE) AS BRANCH,

EMPLOYER_ID,
EMPLOYER,

'LC' AS HIERARCHY_INDICATOR,
Filtered_LC AS HIERARCHY,

FREQUENCY AS PAY_FREQUENCY,

addDays(
    anchor_monday,
    intDiv(
        dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
        14
    ) * 14
) AS PERIOD_START,

addDays(
    addDays(
        anchor_monday,
        intDiv(
            dateDiff('day', anchor_monday, toDate(NEXT_ACTION_DATE)),
            14
        ) * 14
    ),
    13
) AS PERIOD_END,

SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) AS LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,

today() AS DATA_DATE,
now() AS LAST_UPDATE

FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL

WHERE LOAN_STATUS IN ('CURRENT','EXPIRED')
AND FREQUENCY = 'FORTNIGHT' --AND YEAR(NEXT_ACTION_DATE) != 1970

GROUP BY
REGION,
AREA,
BRANCH,
Filtered_LC,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,
PERIOD_END
