--TRUNCATE TABLE UAT_REPLICATED_TABLES.EMPLOYER_PAYDATE_AGGREGATED_METRICS_REPL
--ON CLUSTER 'cluster1'
INSERT INTO UAT_REPLICATED_TABLES.EMPLOYER_PAYDATE_AGGREGATED_METRICS_REPL
(
  COMPANY,
  REGION,
  AREA,
  BRANCH,
  EMPLOYER_ID,
  EMPLOYER,
  HIERARCHY_INDICATOR,
  HIERARCHY,
  PAY_FREQUENCY,
  PERIOD_START,
  PERIOD_END,
  CAPITAL_TOTAL,
  LOANS_COUNT,
  ACTIVE_BRANCHES,
  REPAYMENT_TOTAL,
  NEXT_ACTION_DATES_ARRAY,
  DATA_DATE,
  LAST_UPDATE
)

-- COMPANY LEVEL
SELECT 'COMPANY' AS COMPANY,
'' AS REGION,
'' AS AREA,
'' AS BRANCH,
EMPLOYER_ID AS EMPLOYER_ID,
EMPLOYER AS EMPLOYER,
'COMPANY' AS HIERARCHY_INDICATOR,
'COMPANY' AS HIERARCHY,
FREQUENCY AS PAY_FREQUENCY,
toStartOfMonth(NEXT_ACTION_DATE) AS PERIOD_START,
toLastDayOfMonth(NEXT_ACTION_DATE) AS PERIOD_END,
SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,  
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,
today() AS DATA_DATE,
now() AS LAST_UPDATE
FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL
WHERE LOAN_STATUS IN ('CURRENT','EXPIRED') AND FREQUENCY = 'MONTHLY'
AND toDate(NEXT_ACTION_DATE) BETWEEN toStartOfMonth(today()) AND toStartOfMonth(addMonths(today(), 3))
GROUP BY 
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,PERIOD_END

UNION ALL

-- REGION LEVEL
SELECT 'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS REGION,
'' AS AREA,
'' AS BRANCH,
EMPLOYER_ID AS EMPLOYER_ID,
EMPLOYER AS EMPLOYER,
'REGION' AS HIERARCHY_INDICATOR,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS HIERARCHY,
FREQUENCY AS PAY_FREQUENCY,
toStartOfMonth(NEXT_ACTION_DATE) AS PERIOD_START,
toLastDayOfMonth(NEXT_ACTION_DATE) AS PERIOD_END,
SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,  
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,
today() AS DATA_DATE,
now() AS LAST_UPDATE
FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL
WHERE LOAN_STATUS IN ('CURRENT','EXPIRED') AND FREQUENCY = 'MONTHLY'
AND toDate(NEXT_ACTION_DATE) BETWEEN toStartOfMonth(today()) AND toStartOfMonth(addMonths(today(), 3))
GROUP BY
REGION,
HIERARCHY,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,PERIOD_END
UNION ALL

--AREA LEVEL
SELECT 'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS REGION,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'AreaName', CO_CODE)  AS AREA,
'' AS BRANCH,
EMPLOYER_ID AS EMPLOYER_ID,
EMPLOYER AS EMPLOYER,
'AREA' AS HIERARCHY_INDICATOR,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'AreaName', CO_CODE) AS HIERARCHY,
FREQUENCY AS PAY_FREQUENCY,
toStartOfMonth(NEXT_ACTION_DATE) AS PERIOD_START,
toLastDayOfMonth(NEXT_ACTION_DATE) AS PERIOD_END,
SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,  
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,
today() AS DATA_DATE,
now() AS LAST_UPDATE
FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL
WHERE LOAN_STATUS IN ('CURRENT','EXPIRED') AND FREQUENCY = 'MONTHLY'
AND toDate(NEXT_ACTION_DATE) BETWEEN toStartOfMonth(today()) AND toStartOfMonth(addMonths(today(), 3))
GROUP BY
REGION, AREA,
HIERARCHY,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,PERIOD_END


UNION ALL
--BRANCH LEVEL
SELECT 'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS REGION,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'AreaName', CO_CODE)  AS AREA,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','PastelCode', CO_CODE) AS BRANCH,
EMPLOYER_ID AS EMPLOYER_ID,
EMPLOYER AS EMPLOYER,
'BRANCH' AS HIERARCHY_INDICATOR,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'PastelCode', CO_CODE) AS HIERARCHY,
FREQUENCY AS PAY_FREQUENCY,
toStartOfMonth(NEXT_ACTION_DATE) AS PERIOD_START,
toLastDayOfMonth(NEXT_ACTION_DATE) AS PERIOD_END,
SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,  
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,
today() AS DATA_DATE,
now() AS LAST_UPDATE
FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL
WHERE LOAN_STATUS IN ('CURRENT','EXPIRED') AND FREQUENCY = 'MONTHLY'
AND toDate(NEXT_ACTION_DATE) BETWEEN toStartOfMonth(today()) AND toStartOfMonth(addMonths(today(), 3))
GROUP BY
REGION, AREA, BRANCH, 
HIERARCHY,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,PERIOD_END

UNION ALL
-- LC LEVEL
SELECT 'COMPANY' AS COMPANY,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'RegionName', CO_CODE) AS REGION,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE', 'AreaName', CO_CODE)  AS AREA,
dictGetString('REPLICATED_TABLES.Detailed_BAR_Hierarchy_DICT_BY_T24_CODE','PastelCode', CO_CODE) AS BRANCH,
EMPLOYER_ID AS EMPLOYER_ID,
EMPLOYER AS EMPLOYER,
'LC' AS HIERARCHY_INDICATOR,
Filtered_LC AS HIERARCHY,
FREQUENCY AS PAY_FREQUENCY,
toStartOfMonth(NEXT_ACTION_DATE) AS PERIOD_START,
toLastDayOfMonth(NEXT_ACTION_DATE) AS PERIOD_END,
SUM(CAPITAL_AMOUNT) AS CAPITAL_TOTAL,
COUNT(DISTINCT RECID_LOAN_ID) LOANS_COUNT,
COUNT(DISTINCT CO_CODE) AS ACTIVE_BRANCHES,
SUM(REPAYMENT_TOTAL) AS REPAYMENT_TOTAL,  
groupArray(toDate(NEXT_ACTION_DATE)) AS NEXT_ACTION_DATES_ARRAY,
today() AS DATA_DATE,
now() AS LAST_UPDATE
FROM "REPLICATED_TABLES"."LENDING_TRANSACTIONS_REPL" FINAL
WHERE LOAN_STATUS IN ('CURRENT','EXPIRED') AND FREQUENCY = 'MONTHLY'
AND toDate(NEXT_ACTION_DATE) BETWEEN toStartOfMonth(today()) AND toStartOfMonth(addMonths(today(), 3))
GROUP BY
REGION, AREA, BRANCH,Filtered_LC, 
HIERARCHY,
EMPLOYER_ID,
EMPLOYER,
FREQUENCY,
PERIOD_START,PERIOD_END
