--INSERT INTO UAT_REPLICATED_TABLES.EMPLOYER_PAYDATES_SUBMISSION_HISTORY_REPL
WITH
Submissions AS
(
    SELECT   
    YEAR,MONTH,
    EMPLOYER_ID,
    sumMerge(count_state) AS COUNT,
  	SELECTED_DATE,
    EMPLOYER_PAY_FREQUENCY,
    maxMerge(LAST_UPDATE_STATE) AS LAST_UPDATE
    FROM UAT_REPLICATED_TABLES.HIERARCHY_PAYDATE_COUNTS_AGG_REPL
    WHERE HIERARCHY = 'COMPANY'
    GROUP BY EMPLOYER_PAY_FREQUENCY,YEAR, MONTH, EMPLOYER_ID, SELECTED_DATE
)

-- Monthly
SELECT
YEAR, MONTH,
'COMPANY' AS HIERARCHY,
MONTH AS MONTH_NUM,
CONCAT(YEAR,'-',MONTH) AS MONTH_ORDER,
formatDateTime(toDate(concat(YEAR, '-', MONTH, '-01')), '%Y %b') AS MONTH_NAME,
EMPLOYER_PAY_FREQUENCY,
EMPLOYER_ID,
SUM(`COUNT`) AS Branch_Submissions,
argMax(SELECTED_DATE, tuple(COUNT, LAST_UPDATE)) AS MOST_SELECTED_DATE,
max(COUNT) AS NUMBER_OF_TIMES_DATE_WAS_SELECTED,
now() AS LAST_UPDATE
FROM Submissions
WHERE `COUNT` > 0 AND lower(EMPLOYER_PAY_FREQUENCY) = 'monthly'
GROUP BY YEAR, MONTH,EMPLOYER_PAY_FREQUENCY, EMPLOYER_ID

UNION ALL

--Weekly
SELECT
YEAR,MONTH,
'COMPANY' AS HIERARCHY,
MONTH AS MONTH_NUM,
CONCAT(YEAR,'-',MONTH) AS MONTH_ORDER,
CONCAT(
    formatDateTime(toDate(concat(YEAR, '-', MONTH, '-01')), '%Y %b'),
    ' - Week ',
    toString(toUInt8(((toDayOfMonth(SELECTED_DATE) - 1) / 7) + 1))
) AS MONTH_NAME,
EMPLOYER_PAY_FREQUENCY,
EMPLOYER_ID,
--toStartOfWeek(SELECTED_DATE) AS WEEK_START,
SUM(`COUNT`) AS Branch_Submissions,
argMax(SELECTED_DATE, tuple(COUNT, LAST_UPDATE)) AS MOST_SELECTED_DATE,
max(COUNT) AS NUMBER_OF_TIMES_DATE_WAS_SELECTED,
now() AS LAST_UPDATE

FROM Submissions
WHERE `COUNT` > 0 
AND lower(EMPLOYER_PAY_FREQUENCY) = 'weekly'

GROUP BY
YEAR,MONTH,
'COMPANY' AS HIERARCHY,
EMPLOYER_PAY_FREQUENCY,
EMPLOYER_ID,
toDayOfMonth(SELECTED_DATE)

UNION ALL
-- Fortnight
SELECT
YEAR,MONTH,
'COMPANY' AS HIERARCHY,
MONTH AS MONTH_NUM,
CONCAT(YEAR,'-',MONTH) AS MONTH_ORDER,

CONCAT(
    formatDateTime(toDate(concat(YEAR, '-', MONTH, '-01')), '%Y %b'),
    ' - Fortnight ',
    toString(
        toUInt8(
            ((toUInt8(((toDayOfMonth(SELECTED_DATE)-1)/7)+1)-1)/2)+1
        )
    )
) AS MONTH_NAME,

EMPLOYER_PAY_FREQUENCY,
EMPLOYER_ID,

SUM(`COUNT`) AS Branch_Submissions,
argMax(SELECTED_DATE, tuple(COUNT, LAST_UPDATE)) AS MOST_SELECTED_DATE,
max(COUNT) AS NUMBER_OF_TIMES_DATE_WAS_SELECTED,
now() AS LAST_UPDATE

FROM Submissions

WHERE `COUNT` > 0
AND lower(EMPLOYER_PAY_FREQUENCY) = 'fortnightly'

GROUP BY
YEAR,
MONTH,
EMPLOYER_PAY_FREQUENCY,
EMPLOYER_ID,
toUInt8(((toUInt8(((toDayOfMonth(SELECTED_DATE)-1)/7)+1)-1)/2)+1)
