-- DROP VIEW "UAT_REPLICATED_TABLES"."MV_HIERARCHY_COUNTS" ON CLUSTER 'cluster1' SYNC;

CREATE MATERIALIZED VIEW UAT_REPLICATED_TABLES.MV_HIERARCHY_COUNTS
ON CLUSTER 'cluster1'
TO UAT_REPLICATED_TABLES.HIERARCHY_PAYDATE_COUNTS_REPL
AS
WITH BRANCH_SUBMISSION AS
(
  SELECT
      'COMPANY' AS COMPANY,
      T2.RegionName,
      T2.AreaName,
      T1.BRANCH AS BranchName,
      T1.YEAR,
      T1.MONTH,
      T1.EMPLOYER_ID,
      T1.EMPLOYER_NAME,
      T1.Selected_Date,
      T1.SUBMISSION_FLAG
  FROM 
  (
      SELECT *,
      toDate(CONCAT(toString(YEAR), '-', LPAD(toString(MONTH), 2, '0'), '-', LPAD(toString(DAY), 2, '0'))) AS Selected_Date
        FROM UAT_REPLICATED_TABLES.PAYDATE_EMPLOYER_SUBMISSIONS_REPL
    
  ) AS T1
  LEFT JOIN REPLICATED_TABLES.V_Detailed_BAR_Hierarchy_REPL AS T2
  ON T2.PastelCode = T1.BRANCH 

),
Hierarchy_Explosion AS
(
  SELECT HIERARCHY, YEAR,MONTH, EMPLOYER_ID,EMPLOYER_NAME, Selected_Date, SUBMISSION_FLAG
  FROM BRANCH_SUBMISSION
  ARRAY JOIN
  ([RegionName, AreaName, BranchName, COMPANY]) AS HIERARCHY 
)

SELECT T1.HIERARCHY AS HIERARCHY, T1.YEAR AS YEAR,T1.MONTH AS MONTH, 
T1.EMPLOYER_ID AS EMPLOYER_ID,T1.EMPLOYER_NAME AS EMPLOYER_NAME, T1.Selected_Date AS Selected_Date,  
T2.COUNT + T1.SUBMISSION_FLAG AS COUNT, 
now() AS LAST_UPDATE
FROM Hierarchy_Explosion T1
LEFT JOIN UAT_REPLICATED_TABLES.HIERARCHY_PAYDATE_COUNTS_REPL T2 FINAL
ON T2.YEAR = T1.YEAR
AND T2.MONTH = T1.MONTH
AND T2.EMPLOYER_ID = T1.EMPLOYER_ID
AND T2.HIERARCHY = T1.HIERARCHY
AND T2.Selected_Date = T1.Selected_Date 
