INSERT INTO "REPLICATED_TABLES"."PAYDATES_SUBMISSIONS_REPL"
(
  EMPLOYER_ID,
  YEAR,
  MONTH,
  DAY,
  BRANCH,
  `SUBMISSION_FLAG`,
  EMPLOYER_PAY_FREQUENCY,
  ARRAY_OF_DATES,
  LAST_UPDATE
)

SELECT 
multiIf(toString(dictGetUInt64OrDefault('B2_DICT_DB.temployer_BY_SpecialInstructionNote_DICT', 'Id', EMPLOYER_ID, 0)) != '0', 
toString(dictGetUInt64('B2_DICT_DB.temployer_BY_SpecialInstructionNote_DICT', 'Id', EMPLOYER_ID)), EMPLOYER_ID)AS EMPLOYER_ID,
YEAR,
MONTH,
DAY,
PastelCode AS BRANCH,
1 AS `SUBMISSION_FLAG`,
'MONTHLY' AS EMPLOYER_PAY_FREQUENCY,
[ toDate(concat(YEAR,'-',MONTH,'-',DAY)) ] AS ARRAY_OF_DATES,
now() AS LAST_UPDATE

FROM "REPLICATED_TABLES"."PAYDATE_EMPLOYER_SUCCESS_DATES_REPL" T1
LEFT JOIN "REPLICATED_TABLES"."V_Detailed_BAR_Hierarchy_REPL"  T2
ON T1.CO_CODE = T2.T24_Code

WHERE EMPLOYER_ID != ''
AND YEAR >= 2025 AND MONTH >= 10