--TRUNCATE TABLE "REPLICATED_TABLES"."HIERARCHY_PAYDATE_COUNTS_REPL";

INSERT INTO "REPLICATED_TABLES"."HIERARCHY_PAYDATE_COUNTS_REPL"
(
  HIERARCHY,
  YEAR,
  MONTH,
  EMPLOYER_ID,
  Selected_Date,
  `COUNT`,
  LAST_UPDATE
)

WITH ALL_BRANCH_SUBMISSION_COUNTS AS 
(
  SELECT 
  T1.YEAR, T1.MONTH, 'COMPANY' AS COMPANY,
  T2.RegionName AS REGION,T2.AreaName AS AREA,
  T2.PastelCode AS BRANCH,
  T1.EMPLOYER_ID, 
  toDate(CONCAT(toString(YEAR), '-', LPAD(toString(MONTH), 2, '0'), '-', LPAD(toString(DAY), 2, '0'))) AS Selected_Date,
  SUM(SUBMISSION_FLAG) AS BRANCH_SUBMISSION_COUNT_PER_BRANCH
  FROM "REPLICATED_TABLES"."PAYDATE_EMPLOYER_SUBMISSIONS_REPL_V2" T1 FINAL
  LEFT JOIN  "REPLICATED_TABLES"."V_Detailed_BAR_Hierarchy_REPL" T2
  ON T2.PastelCode = T1.BRANCH
  WHERE T2.PastelCode <> ''
  GROUP BY YEAR, MONTH, REGION, AREA, BRANCH, EMPLOYER_ID, Selected_Date
),

BRANCH_COUNT_PER_BRANCH AS
(
  SELECT 
  BRANCH AS HIERARCHY,
  YEAR, MONTH, 
  EMPLOYER_ID,
  Selected_Date, SUM(BRANCH_SUBMISSION_COUNT_PER_BRANCH) AS COUNT,
  now() AS  LAST_UPDATE 
  FROM ALL_BRANCH_SUBMISSION_COUNTS
  GROUP BY YEAR, MONTH, BRANCH, EMPLOYER_ID,  Selected_Date
),

BRANCH_COUNT_PER_AREA AS
(
  SELECT 
  AREA AS HIERARCHY,
  YEAR, MONTH, 
  EMPLOYER_ID,
  Selected_Date, SUM(BRANCH_SUBMISSION_COUNT_PER_BRANCH) AS COUNT,
  now() AS  LAST_UPDATE 
  FROM ALL_BRANCH_SUBMISSION_COUNTS
  GROUP BY YEAR, MONTH, AREA, EMPLOYER_ID,  Selected_Date
),

BRANCH_COUNT_PER_REGION AS
(
  SELECT 
  REGION AS HIERARCHY,
  YEAR, MONTH,
  EMPLOYER_ID,
  Selected_Date, SUM(BRANCH_SUBMISSION_COUNT_PER_BRANCH) AS COUNT,
  now() AS  LAST_UPDATE 
  FROM ALL_BRANCH_SUBMISSION_COUNTS
  GROUP BY YEAR, MONTH, REGION, EMPLOYER_ID,  Selected_Date
),

BRANCH_COUNT_PER_COMPANY AS
(
  SELECT 
  COMPANY AS HIERARCHY,
  YEAR, MONTH,
  EMPLOYER_ID,
  Selected_Date, SUM(BRANCH_SUBMISSION_COUNT_PER_BRANCH) AS COUNT,
  now() AS  LAST_UPDATE
  FROM ALL_BRANCH_SUBMISSION_COUNTS
  GROUP BY YEAR, MONTH, COMPANY, EMPLOYER_ID,  Selected_Date
)

SELECT * FROM BRANCH_COUNT_PER_BRANCH
UNION ALL
SELECT * FROM BRANCH_COUNT_PER_AREA
UNION ALL
SELECT * FROM BRANCH_COUNT_PER_REGION
UNION ALL
SELECT * FROM BRANCH_COUNT_PER_COMPANY
